" Vim entry point. Loads shared init configs, then declares plugins via
" vim-plug. Plugin list lives in plugins/vim.vim.

filetype plugin indent on
runtime! init/**.vim

call plug#begin('~/.vim/plugged')
runtime plugins/vim.vim
call plug#end()

colorscheme grb256
